'use client';
import { motion } from 'framer-motion';
import Typed from 'typed.js';
import { JOBS, TESTIMONIALS, FEATURES, STATS, PRICING_PLANS, FAQ } from '@/lib/constants';
import { ChevronDown, Star, CheckCircle } from 'lucide-react';
import React, { useState, useEffect } from 'react';

export default function Home() {
  const [email, setEmail] = useState('');
  const [expandedFAQ, setExpandedFAQ] = useState<number | null>(null);
  useEffect(() => { const typed = new Typed('.typed-headline', { strings: ['DevOps Engineer', 'Security Expert', 'ML Engineer'], typeSpeed: 50, backSpeed: 30, loop: true }); return () => typed.destroy(); }, []);
  return (<div className="bg-dark text-white min-h-screen">
    <nav className="fixed top-0 w-full z-50 bg-dark/80 backdrop-blur-md border-b border-green-primary/20 px-4 py-3"><div className="max-w-7xl mx-auto flex justify-between items-center"><div className="text-2xl font-bold text-green-primary">🎯 Job Digest</div><button className="bg-green-primary text-dark px-6 py-2 rounded-lg font-semibold">Join</button></div></nav>
    <section className="min-h-screen flex items-center justify-center pt-20"><div className="text-center px-4"><h1 className="text-5xl md:text-7xl font-bold mb-6">Find Your Next <span className="typed-headline text-green-primary"></span></h1><p className="text-xl text-gray-300 mb-8 max-w-2xl">AI job matching across 50+ boards with auto-generated cover letters.</p><button className="bg-green-primary text-dark px-8 py-3 rounded-lg font-semibold">🚀 Start Free</button></div></section>
    <section className="py-20 bg-surface"><div className="max-w-6xl mx-auto px-4"><h2 className="text-4xl font-bold text-center mb-12">By The Numbers</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-8">{STATS.map((s, i) => (<div key={i} className="text-center p-6 bg-dark rounded-xl border border-green-primary/20"><div className="text-4xl font-bold text-green-glow mb-2">{s.value}{s.suffix}</div><p className="text-gray-400">{s.label}</p></div>))}</div></div></section>
    <section className="py-20 px-4"><div className="max-w-6xl mx-auto"><h2 className="text-4xl font-bold text-center mb-12">Features</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{FEATURES.map((f, i) => (<div key={i} className="p-6 bg-surface rounded-xl border border-green-primary/20 hover:border-green-primary transition"><div className="text-4xl mb-4">{f.icon}</div><h3 className="text-xl font-semibold text-green-primary mb-2">{f.title}</h3><p className="text-gray-400">{f.description}</p></div>))}</div></div></section>
    <section className="py-20 px-4 bg-surface/50"><div className="max-w-6xl mx-auto"><h2 className="text-4xl font-bold text-center mb-12">Real Jobs</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{JOBS.map((j, i) => (<div key={i} className="p-6 bg-dark rounded-xl border border-green-primary/20"><div className="flex justify-between mb-4"><div><h3 className="font-semibold">{j.title}</h3><p className="text-sm text-gray-400">{j.company}</p></div><span className="text-2xl font-bold text-green-glow">{j.match}%</span></div><p className="text-sm text-gray-400">{j.location}</p></div>))}</div></div></section>
    <section className="py-20 px-4"><div className="max-w-6xl mx-auto"><h2 className="text-4xl font-bold text-center mb-12">Stories</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TESTIMONIALS.map((t, i) => (<div key={i} className="p-6 bg-surface rounded-xl border border-green-primary/20"><div className="flex gap-1 mb-4">{[...Array(5)].map((_, j) => (<Star key={j} size={16} className="text-yellow-400 fill-yellow-400" />))}</div><p className="text-gray-300 italic mb-4">"{t.quote}"</p><div className="flex gap-2"><span className="text-3xl">{t.image}</span><div><p className="font-semibold text-sm">{t.name}</p><p className="text-xs text-gray-400">{t.role}</p></div></div></div>))}</div></div></section>
    <section className="py-20 px-4 bg-surface/50"><div className="max-w-3xl mx-auto"><h2 className="text-4xl font-bold text-center mb-12">FAQ</h2>{FAQ.map((q, i) => (<div key={i} className="mb-4 bg-dark rounded-xl border border-green-primary/20"><button onClick={() => setExpandedFAQ(expandedFAQ === i ? null : i)} className="w-full p-4 flex justify-between items-center hover:bg-surface"><p className="font-semibold text-left">{q.question}</p><ChevronDown size={20} className={expandedFAQ === i ? "rotate-180" : ""} /></button>{expandedFAQ === i && <div className="px-4 pb-4 text-gray-400 border-t border-green-primary/10">{q.answer}</div>}</div>))}</div></section>
    <section className="py-20 px-4"><div className="max-w-5xl mx-auto"><h2 className="text-4xl font-bold text-center mb-12">Pricing</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{PRICING_PLANS.map((p, i) => (<div key={i} className={`p-8 rounded-xl border transition ${p.popular ? "border-green-primary bg-green-primary/10 shadow-glow" : "border-green-primary/20 bg-surface"}`}><h3 className="text-2xl font-bold mb-2">{p.name}</h3><div className="text-4xl font-bold text-green-primary mb-4">{p.price}</div><ul className="space-y-3 mb-8">{p.features.map((f, j) => (<li key={j} className="flex gap-2"><CheckCircle size={16} className="text-green-primary flex-shrink-0 mt-0.5" /><span className="text-sm">{f}</span></li>))}</ul><button className={`w-full py-2 rounded-lg font-semibold ${p.popular ? "bg-green-primary text-dark" : "border border-green-primary text-green-primary hover:bg-green-primary hover:text-dark"}`}>{p.cta}</button></div>))}</div></div></section>
    <section className="py-20 px-4"><div className="max-w-2xl mx-auto text-center"><h2 className="text-4xl font-bold mb-6">Ready?</h2><p className="text-gray-300 mb-8">Join thousands of engineers finding perfect matches.</p><div className="flex gap-4"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Enter email" className="px-6 py-3 bg-dark rounded-lg border border-green-primary/50 focus:border-green-primary outline-none flex-1" /><button className="bg-green-primary text-dark px-8 py-3 rounded-lg font-semibold">Join Now</button></div></div></section>
    <footer className="bg-darker border-t border-green-primary/20 py-12 px-4 text-center text-gray-500"><p>&copy; 2026 Job Digest. Built with 💚</p></footer>
  </div>);
}
